version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend-db:/workspace
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////workspace/ps5_hunter.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  backend-db:
